dist: bionic
language: python
python:
  - "3.6"      # current default Python on Travis CI
  
# command to install dependencies
install:
  - pip install -r src/requirements.txt

script:
  - cd src
  - python Scraping_covid19.py
  - cd ..

deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  github-token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: master
  verbose: true
  commit_message: "[ci skip] Actualizacion Automatizada by TravisBOT"

notifications:
  email: false