dist: bionic
language: python
python:
  - "3.6"      # current default Python on Travis CI
  
# command to install dependencies
install:
  - pip install -r src/requirements.txt

script:
  - cd src
  - python Scraping_covid19.py
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master

notifications:
  email: false